class exception_main(Exception):
    '''main exception class'''
    pass

class connection_error(exception_main):
    '''Connection error occured'''
    pass